language: go
go:
        - 1.16.x
install:
        - mkdir $HOME/src
        - cd $HOME/src
        - git clone https://github.com/gohugoio/hugo.git
        - cd hugo
        - go install
script:
        - mkdir -p themes/beautifulhugo && git clone https://GitHub.com/halogenica/beautifulhugo.git themes/beautifulhugo
        - hugo --theme beautifulhugo
deploy:
        provider: pages
        skip_cleanup: true
        GitHub_token: $GITHUB_TOKEN
        keep_history: true
        on:
                branch: master